# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none  # Disable until we are ready to work on this

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '1b52fe63-22c6-4651-a6ac-2f958eddaf28'

  webAppName: 'frontend-odyssey'

  environmentName: 'frontend-odyssey'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)

      steps:
        - task: PublishBuildArtifacts@1
          displayName: 'Publish build artifacts'
          inputs:
            pathToPublish: '$(System.DefaultWorkingDirectory)'
            artifactName: 'drop/$(Build.BuildId).zip'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: $(environmentName)
      pool:
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureWebApp@1
                displayName: 'Azure Web App Deploy: rc-front-end-app-service'
                inputs:
                  azureSubscription: $(azureSubscription)
                  appType: webAppLinux
                  appName: $(webAppName)
                  runtimeStack: 'NODE|18.x'
                  package: $(Build.ArtifactName)
                  startUpCommand: 'yarn start'
